project_name: ncryp
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/ncryp
    binary: ncryp
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
brews:
  - name: ncryp # CLI name
    github:
      owner: nobishino
      name: homebrew-tap
    url_template: "https://github.com/nobishino/ncryp/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author: # homebrew-tapにcommitするときに使うGitHubアカウント
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    # homepage:
    description: "Weak Cryptography CLI for Learners." # 適当なdescription
    test: |
      system "#{bin}/ncryp --version"
    install: | # Goならばバイナリ名でOK
      bin.install "ncryp"
